### ISSUE TITLE
Adding CodeSnippet Plugin

### ISSUE THREAD

**Issue by ttseng** [galetahub/ckeditor#531]
I haven't been able to configure CKEditor to include the CodeSnippet plugin.  When I try to load the CKEditor, I get the following errors in my Javascript console:

```
Uncaught TypeError: undefined is not a function
```

referring to the following line of widgets/plugin.js

```
CKEDITOR.style.addCustomHandler( {
```

and another error with this line of codesnippets/plugin.js:

```
editor.addContentsCss( path + 'lib/highlight/styles/' + editor.config.codeSnippet_theme + '.css' );
```

Here is my current configuration:

app/assets/javascripts/ckeditor/config.js:

```
CKEDITOR.editorConfig = function (config) {
// ... other configuration ...

config.toolbar_mini = [
  ["Bold",  "Italic",  "Underline", "-",  "NumberList",  "BulletList", "Link", "Unlink", "CodeSnippet", "RemoveFormat"],
];
config.toolbar = "simple";
}
```

config/initializers/ckeditor.rb:

```
Ckeditor.setup do |config|
  config.assets_languages = ['en']
  config.assets_plugins = ['widget', 'dialog', 'dialogui', 'lineutils', 'codesnippet']
  #handle custom addons
  assets_root =  Rails.root.join('app','assets','javascripts')
  ckeditor_plugins_root = assets_root.join('ckeditor','plugins')
  %w(openlink sourcedialog).each do |ckeditor_plugin|
    Ckeditor.assets += Dir[ckeditor_plugins_root.join(ckeditor_plugin, '**', '*.js')].map {|x| x.sub(assets_root.to_path, '').sub(/^\/+/, '')}
   end
end
```

view.html.erb:

```
    <%= f.cktext_area :description, :ckeditor => {:toolbar => 'mini'}%>
```

**Comment by CodedBeardedSignedTaylor** [comment]
+1 to this. 

The only way to do this is apparently to remove the gem and install a custom version of Ckeditor. Is there any way that you can take a custom build and replace it with the gem's version? Totally scared of messing up the backend in the process.

**Comment by ttseng** [comment]
@CodedBeardedSignedTaylor that's exactly what I ended up doing - I totally removed the gem and used a custom version of CKeditor with the codesnippet already added.  It was a pain, but it was the only way I could get it work.

**Comment by CodedBeardedSignedTaylor** [comment]
@ttseng Did you have any problem with the backend of your app?

**Comment by CodedBeardedSignedTaylor** [comment]
Quick fix here: You can add highlight.js into your application via CDN and use Ckeditor's source function to add code to your application. It might take a bit of tweaking to get right, but its certainly better than just removing the gem completely. 

I've also submitted a pull request with code that add's CodeSnippet to the default ckeditor package.

**Comment by ahnbizcad** [comment]
+1

As far as a clean way to do things, I would imagine it woudld be downloading your own custom CKeditor, hosting it on CDN, and including it via a script tag, right? Are there any CDNs that are cheap?

That way, you don't have to mess with the gem, nor manually convert the downloaded CKeditor to be compatible with the asset pipeline (btw, is this the root of it being "a total pain"?

**Comment by darmens** [comment]
+1

**Comment by darmens** [comment]
It works! Here is my setup:

```ruby
# Gemfile
gem 'ckeditor', git: 'https://github.com/galetahub/ckeditor', branch: 'master'
```
In app/assets/javascripts/ckeditor/plugins I downloaded and estracted [codesnippet](http://ckeditor.com/addon/codesnippet] and its dependencies, namely: [widget](http://ckeditor.com/addon/widget), [lineutils](http://ckeditor.com/addon/lineutils] and clipboard. Be aware that, for each plugin, you must download its version compatible with the one of ckeditor included with the gem. You can find out the exact version of ckeditor with javascript, calling `CKEDITOR.version` and then check the compatibility table available in the dowload page of the plugins.

```javascript
// app/assets/javascripts/ckeditor/config.js
config.extraPlugins = 'codesnippet';
// ...
// Toolbar groups configuration.
  config.toolbar = [
    { name: 'document', groups: [ 'mode', 'document', 'doctools' ], items: [ 'Source', 'CodeSnippet'] },
// ...
```
I think this is not mandatory, but I also added this line:
```ruby
# config/initializers/ckeditor.rb
config.assets_plugins = ['widget', 'dialog', 'dialogui', 'lineutils', 'codesnippet']
```
Then I downloaded and installed a [customized highlight.js download](https://highlightjs.org/download/). In particular I extracted the downloaded package and putted only the needed files in a directory under `/public` because they doesn't need to be precompiled, and so, they doesn't need to go through the asset pipeline. The highlight.js file was already minified, but I had to minify myself the css one (the theme). I don't know if this is the best option but it worked for me.

Finally, I added the following lines  in the `head` section of the views where a code snippet is rendered (referencing the files of highlight in the `public/javascripts` folder):

```html
<link rel="stylesheet" href="/javascripts/highlight/styles/theme_name_of_choice.min.css">
<script src="/javascripts/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```
Hope this helps saving some time to somebody! :smile:

**Comment by moeabdol** [comment]
@darmenise Thank you for sharing your instructions. I believe your method is right and I did follow them, but it still doesn't work.

I noticed that the problem is not with your instructions, but rather with my config.js which is never loaded.

In my application.js I have
```
= require ckeditor/init
= require ckeditor/config
```

When I remove the first line ckeditor/init to force my application to load my configs instead, I get CKEDITOR Undefined error, because my first line in the config.js is:
`CKEDITOR.editorConfig = function( config ) { ..... }`

Thus I found out that my custom configurations inside config.js was never loaded, but instead it was init that was loaded all the time with the default CKeditor configs.

Do you have any idea why my config is never loaded? and how I can possibly fix that.
Thanks

Note: My config.js is under `app/assets/javascripts/ckeditor/config.js`
