### ISSUE TITLE
Problems in adding new plugin for Ckeditor

### ISSUE THREAD

**Issue by pardeep2690** [galetahub/ckeditor#618]
i am trying to add Mathematical  Formula plugin to my rails app after downloading plugin and and copying it to
app/assets/javascripts/ckeditor/plugins 
and then adding settings to 
app/assets/javascripts/ckeditor/config.js
CKEDITOR.editorConfig = function( config )
{

  config.extraPlugins = 'mathjax';

}

but it doesn't working

**Comment by cytomich** [comment]
@pardeep2690 I am always put ckeditor plugins in `lib/assets/javascripts/ckeditor/plugins`

**Comment by tannerj** [comment]
I was also having trouble getting the 'save' plugin to work. Turns out, using the same setup as @pardeep2690 I still had to add the save item to 'app/assets/javascripts/ckeditor/config.js' The line I altered looks like this:

`config.toolbar = [
{ name: 'document', groups: [ 'mode', 'document', 'doctools' ], items: [ 'Source', '**Save**'] },`

Notice the addition of the save item. I'm not sure how to add mathjax to the ui, but I think you'll have to manually add the button.

After doing some testing, commenting out the config.toolbar section found here: 
https://github.com/galetahub/ckeditor/blob/master/app/assets/javascripts/ckeditor/config.js
starting on line 37 allowed the save button to show. I think the fact that the default config.js file explicitly defines config.toolbar, means that you have to override the default by creating your own app/assets/javascripts/config.js file and either leaving the config.toolbar section blank, or inserting your plugin where you want it.
