### ISSUE TITLE
image send it to the server doesn't work. alert says "data can't be blank"

### ISSUE THREAD

**Issue by HochunNN** [galetahub/ckeditor#674]
I'm new to the rails
and after installing gem, I tried to upload image. but I get this error..."data can't be blank"
I'm trying to use carrierwave and aws s3.(I think I followed instructions correctly)
do you guys have any idea??

I'm sorry that Im not good at explaining my situation if you need more of my project information please tell me I will update it right away.

**Comment by HochunNN** [comment]
I just found out that if I click the send it to the server, it saves it in my public/uploads/tmp folder...

what is going on... :(

**Comment by mikewagz** [comment]
I am also seeing this error after a file selection is made with the "attach" plugin.  The request hits the server, but this error occurs:

`
DEPRECATION WARNING: `render :text` is deprecated because it does not actually render a `text/plain` response. Switch to `render plain: 'plain text'` to render as `text/plain`, `render html: '<strong>HTML</strong>'` to render as `text/html`, or `render body: 'raw'` to match the deprecated behavior and render with the default Content-Type, which is `text/plain`. (called from respond_with_asset at /Users/michaelwagstaff/Developer/Rails/spectora/vendor/bundle/ruby/2.3.0/bundler/gems/ckeditor-2dfb02f29fd8/app/controllers/ckeditor/application_controller.rb:17)`

**Comment by leofrozenyogurt** [comment]
still experiencing this issue on rails 5

**Comment by leofrozenyogurt** [comment]
@HochunNN just wondering why did you close the issue? where you able to resolve?

**Comment by lanqiu1986** [comment]
I had this same problem,@HochunNN, how do you resolve it? Could you share it? Thank you very much!!!

**Comment by rpbaptist** [comment]
The same problem occurs when creating uploads from `rails console`:

Something is wrong with the Carrierwave integration.

**Comment by af23me** [comment]
In my case I received this error due not installed `imagemagic`. After installation all good.
