### ISSUE TITLE
Invalid single-table inheritance type: Ckeditor::Picture is not a subclass of Ckeditor::Picture

### ISSUE THREAD

**Issue by victor0402** [galetahub/ckeditor#680]
I'm getting this error when I try to browse the server files:
```
Showing /home/dev/.rvm/gems/ruby-2.3.1/gems/ckeditor-4.2.0/app/views/ckeditor/pictures/index.html.erb where line #9 raised:

Invalid single-table inheritance type: Ckeditor::Picture is not a subclass of Ckeditor::Picture
```

I'm using `rails 5.0.0` and `ckeditor gem 4.2.0` with paperclip and ActiveRecord.

File upload works fine. Only when I try to browse the files I'm getting the error above.

My models are the generated ones:
```
app
 |_models
     |__ckeditor
          |__asset.rb
          |__attachment_file.rb
          |__picture.rb
```

Is this an issue with rails 5.0.0 or should I do something else?

**Comment by galetahub** [comment]
Hm, I will check it soon

**Comment by victor0402** [comment]
@galetahub On a new project I got no error. So, looks like my app is causing the problem. I'll try to figure out what's happening. I'm sorry for the false alarm.

**Comment by pauldoerwald** [comment]
I'm having the same issue, but it seems intermittent. I was able to reproduce it with these steps:

1. Start the server (rails s)
2. In ckeditor, click "Browse Server" on Image Properties
3. Everything works.
4. View the page I created with the image.
5. Edit the page again in ckeditor, clicking on Image Properties and Browse Server
6. Witness the error in all its glory.

I'm running Rails 5.0.0.1 development mode, which is what I think the source of the problem is. That is, I suspect this issue won't happen in production, although I can't test that yet.

**Comment by Extrapolator214** [comment]
```
class Ckeditor::Picture < Ckeditor::Asset

  def self.inheritance_column
    nil
  end
end
```
Does this help? I encountered the same problem, it seems to solve the error for me.

**Comment by wcmolina** [comment]
I'm also getting this error (Rails 5.0.1, gem version 4.2.2). I reproduced the error following the steps @pauldoerwald described in his comment. However, the error only happens if I edit the `ckeditor_picture_uploader.rb` file by adding the following:

`process resize_to_fill: [800, 0]`

AFTER this line

`process :extract_dimensions`

which changes the picture's dimensions originally stored in the database. If I leave it before that line, the error no longer occurs. Maybe this has anything to do?

**Comment by OrbitalStudios** [comment]
Why was this closed? This is still an issue 100%.
