### ISSUE TITLE
Upload image not work in Rails 5

### ISSUE THREAD

**Issue by kaanoo2904** [galetahub/ckeditor#692]
I created a blank project from scratch, add these gem:

```
gem 'mini_magick'
gem 'carrierwave'
gem 'ckeditor'
```

And follow any tutorial in README.

When trying to insert an image to a field, if I chose to upload from "image info" tab, image loading spinner just spins forever.

![image](https://cloud.githubusercontent.com/assets/10462294/18669719/97f14eb4-7f66-11e6-8c2a-142ee8391103.png)

In the console, transaction immediately rollbacks without any error message.

![image](https://cloud.githubusercontent.com/assets/10462294/18669758/be758834-7f66-11e6-89b2-aed74ae10ac0.png)

If I chose to upload directly in "upload" tab, it returns this error:

![image](https://cloud.githubusercontent.com/assets/10462294/18669789/e63ca38e-7f66-11e6-98a4-b827419474d6.png)

Again, no transaction error messae in console

![image](https://cloud.githubusercontent.com/assets/10462294/18669805/fb6f81e0-7f66-11e6-8c1e-3770b7760615.png)

**Comment by kaanoo2904** [comment]
After some research, I found out that from Rails 5 , belongs_to associations now is enforced.

I saw that someone has made a pull request about this ?

https://github.com/galetahub/ckeditor/pull/683

**Comment by ugran** [comment]
I have same problem.

Please merge the fix.

**Comment by dmerrill6** [comment]
Same problem here. 

Has anybody found a hotfix meanwhile?

**Comment by fifiteen82726** [comment]
But the PR has 1 failing check.

**Comment by zhorn** [comment]
Someone found how to fix it?

**Comment by galetahub** [comment]
Just pushed new commits, check out this

**Comment by zhorn** [comment]
Still got the same issue :/

**Comment by galetahub** [comment]
What rails version are you using?
Can you provide request log?

**Comment by zhorn** [comment]
Rails 5.0.0.1

Started POST "/ckeditor/pictures?CKEditor=article_content&CKEditorFuncNum=1&langCode=pt-br" for 127.0.0.1 at 2016-10-11 12:12:07 -0300
Processing by Ckeditor::PicturesController#create as HTML
  Parameters: {"upload"=>#<ActionDispatch::Http::UploadedFile:0x007f072c355ab8 @tempfile=#<Tempfile:/tmp/RackMultipart20161011-24208-n8izrv.jpg>, @original_filename="plansul-logo.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"upload\"; filename=\"plansul-logo.jpg\"\r\nContent-Type: image/jpeg\r\n">, "ckCsrfToken"=>"uEnbz77ciIfK0X8843H6H6QbGN6gDCs6Mb4N2iBG", "CKEditor"=>"article_content", "CKEditorFuncNum"=>"1", "langCode"=>"pt-br"}
dads
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-24208-1sz58x3.jpg'
Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-24208-ac18hy.jpg[0]' 2>/dev/null
Command :: PATH=/usr/local/bin/:$PATH; identify -format %m '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-24208-ac18hy.jpg[0]'
Command :: PATH=/usr/local/bin/:$PATH; convert '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-24208-ac18hy.jpg[0]' -auto-orient -resize "800>" '/tmp/77d24ba96ca9bc2244802e571801762f20161011-24208-14jm2a3'
Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-24208-ac18hy.jpg[0]' 2>/dev/null
Command :: PATH=/usr/local/bin/:$PATH; identify -format %m '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-24208-ac18hy.jpg[0]'
Command :: PATH=/usr/local/bin/:$PATH; convert '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-24208-ac18hy.jpg[0]' -auto-orient -resize "x100" -crop "118x100+125+0" +repage '/tmp/77d24ba96ca9bc2244802e571801762f20161011-24208-62lx7q'
   (0.1ms)  begin transaction
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-24208-l5nw40.jpg'
   (0.1ms)  rollback transaction
DEPRECATION WARNING: `render :text` is deprecated because it does not actually render a `text/plain` response. Switch to `render plain: 'plain text'` to render as `text/plain`, `render html: '<strong>HTML</strong>'` to render as `text/html`, or `render body: 'raw'` to match the deprecated behavior and render with the default Content-Type, which is `text/plain`. (called from respond_with_asset at /home/plansul2/.bundle/ruby/2.3.0/ckeditor-2dfb02f29fd8/app/controllers/ckeditor/application_controller.rb:17)
  Rendering text template
  Rendered text template (0.0ms)
Completed 200 OK in 79ms (Views: 1.2ms | ActiveRecord: 1.5ms)

**Comment by galetahub** [comment]
@zhorn try to run command:
```
bundle update ckeditor
```
Then restart rails server and try again, please

**Comment by zhorn** [comment]
The bundle updated to new 4.2.1 version but the error remains.


Started POST "/ckeditor/pictures?CKEditor=article_content&CKEditorFuncNum=1&langCode=pt-br" for 127.0.0.1 at 2016-10-11 13:31:49 -0300
Processing by Ckeditor::PicturesController#create as HTML
  Parameters: {"upload"=>#<ActionDispatch::Http::UploadedFile:0x007f8f582faa78 @tempfile=#<Tempfile:/tmp/RackMultipart20161011-25377-1kyfs2g.jpg>, @original_filename="plansul-logo.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"upload\"; filename=\"plansul-logo.jpg\"\r\nContent-Type: image/jpeg\r\n">, "ckCsrfToken"=>"uEnbz77ciIfK0X8843H6H6QbGN6gDCs6Mb4N2iBG", "CKEditor"=>"article_content", "CKEditorFuncNum"=>"1", "langCode"=>"pt-br"}
dads
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-25377-ibawu5.jpg'
Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-25377-19d8ysh.jpg[0]' 2>/dev/null
Command :: PATH=/usr/local/bin/:$PATH; identify -format %m '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-25377-19d8ysh.jpg[0]'
Command :: PATH=/usr/local/bin/:$PATH; convert '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-25377-19d8ysh.jpg[0]' -auto-orient -resize "800>" '/tmp/31719799bf6553b93e1fd02be20c97c120161011-25377-1ebslsi'
Command :: PATH=/usr/local/bin/:$PATH; identify -format '%wx%h,%[exif:orientation]' '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-25377-19d8ysh.jpg[0]' 2>/dev/null
Command :: PATH=/usr/local/bin/:$PATH; identify -format %m '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-25377-19d8ysh.jpg[0]'
Command :: PATH=/usr/local/bin/:$PATH; convert '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-25377-19d8ysh.jpg[0]' -auto-orient -resize "x100" -crop "118x100+125+0" +repage '/tmp/31719799bf6553b93e1fd02be20c97c120161011-25377-rpn43g'
   (0.1ms)  begin transaction
Command :: PATH=/usr/local/bin/:$PATH; file -b --mime '/tmp/13a36678454ebe2cc292ab83cee3947e20161011-25377-19ca5mm.jpg'
   (0.1ms)  rollback transaction
  Rendering html template
  Rendered html template (0.0ms)
Completed 200 OK in 78ms (Views: 1.1ms | ActiveRecord: 0.8ms)

**Comment by zhorn** [comment]
I noticed a difference in my problem and in the original poster.

In my output i see the commands who must be executed by the imagemagick, perhaps the commands not been executed and this is causing the trouble. Someone can say if it's the real problem? And if is how can i resolve this?

**Comment by ugran** [comment]
Yeah same here...

The error message is different.

Just rollbacks the transaction and says in JS popup "assetable must exist".

**Comment by zhorn** [comment]
I changed from paperclip to carrierwave + mini_magick and i still got the same issue.

**Comment by BBBernsteyn** [comment]
PR https://github.com/galetahub/ckeditor/pull/683 solves the issue on Rails 5 for me. Kindly merge @kaanoo2904's changes. Thanks for your hard work!!!

**Comment by alexdzh** [comment]
Added:
belongs_to :assetable, polymorphic: true, optional: true
Transaction still rollback

**Comment by ugran** [comment]
I changed the gem locally this way: http://stackoverflow.com/a/20342682

#683 solved for me.

**Comment by iliahmarc** [comment]
#683 as mentioned above also worked for me. Much appreciated!

**Comment by kaanoo2904** [comment]
@alexdzh I forked this repo before , you could try it :)

https://github.com/kaanoo2904/ckeditor

**Comment by galetahub** [comment]
Try new gem version 4.2.1.

**Comment by tuballeonel** [comment]
No rails 5
utilizei optional: true
belongs_to :company, optional: true

**Comment by kevinhq** [comment]
> Try new gem version 4.2.1.

I am on version 4.3.0 with Rails 5.2.3 and still got exactly same error as the OP.

I used it with carrierwave backend.
