### ISSUE TITLE
Why is assetable association removed

### ISSUE THREAD

**Issue by botularius** [galetahub/ckeditor#788]
In Version 4.2.1 you removed the following:
- Remove polymorphic assetable association
- Remove ckeditor_before_create_asset callback in controller

I understand that with rails 5 a belongs_to is now required as default. But why did you not only set optional: true to the belongs_to of assetable:
`belongs_to :assetable, polymorphic: true, optional: true`

I actually need a relation to a User model in order to filter only for pictures uploaded only by a specific users (Other users should not see the uploaded pictures of me).

Any ideas or workarounds for that?
I could patch this gem and add the belongs_to :assetable again. But I would rather not do that!

**Comment by patricklindsay** [comment]
@galetahub Any ideas?

**Comment by tonycchung** [comment]
FWIW, 

I essentially reverted the changes made here:
https://github.com/galetahub/ckeditor/commit/4992843a997ba4d1062a26145af2bcd3e1b96238?diff=split#diff-71da890a36d4ef20308bfb137b87197fL14

to retain the polymorphic assetable association. this was required so that you can scope your pictures#index via asset_id (aka allow current_user to see only his/her uploaded pictures)

not sure why this was removed, it seems like a pretty important feature to keep
