### ISSUE TITLE
Rails 6: ckeditor is not work after updating to rails 6

### ISSUE THREAD

**Issue by ayza-hamid** [galetahub/ckeditor#871]
### ✔️ Expected result

*Ckeditor should work properly, I updated to the latest version of ckeditor and configured accordingly.*

### ❌ Actual result

*Uncaught ReferenceError: CKEDITOR is not defined. I am getting this error on the console.*

## 📃 Other details

* **Browser**: Chrome
* **OS**: Ubuntu 16.04 LTS
* **CKEditor** version: 5.0.0

---

**Comment by maurosbu** [comment]
@ayza-hamid I finished upgrading a Rails app to version 6.0.1 and I don't have this issue.

Did you set cdn_url in **config/initializers/ckeditor.rb** initializer?

    Ckeditor.setup do |config|    

        ...

        # CKEditor CDN
        # More info here http://cdn.ckeditor.com/
        # By default: nil (CDN disabled)
        config.cdn_url = '//cdn.ckeditor.com/4.13.0/full/ckeditor.js'

        ...

    end

Version 5.0.0 of the gem is a CDN only release.

**Comment by nitsujri** [comment]
The JS error CKEDITOR not defined is commonly a load order issue. i.e. the config was loaded before the library was loaded. 

If you are loading it via Webpacker you'll want to do a `window.addEventListener('load', () => { ... load ...})`

Otherwise you'll need to post your config files and JS load tags.
